from datetime import datetime, timedelta
import csv

from getData import API


processedSchedule = {}


def main(code, cache, token):
    api = API("https://aeroapi.flightaware.com", token)
    if cache:
        data = api.fetchSchedule()
    else:
        data = api.getSchedule()

    writer, f = initCSV(code, len(data))

    processData(data)
    writeData(processedSchedule, writer)

    f.close()

    print("Data has been successfully written to schedule.csv")


def writeData(data, writer):
    for flight in data.values():
        writer.writerow(flight)


def processData(schedule):
    for flight in schedule:
        processedFlight = processedSchedule.get(flight["flight_number"], {})

        if not processedFlight:
            processedFlight["number"] = flight["flight_number"]
            processedFlight["dep"] = flight["origin"]["code_icao"].strip()
            processedFlight["arr"] = flight["destination"]["code_icao"].strip()
            processedFlight["type"] = "pax"
            processedFlight["duration"] = round(flight["filed_ete"] / 60, 1)
            processedFlight["airframes"] = flight["aircraft_type"].strip()

        date = datetime.fromisoformat(flight["scheduled_off"][:-1])
        dayOfTheWeek = date.weekday()

        daysOfTheWeek = ["mon", "tue", "wed", "thu", "fri", "sat", "sun"]

        for i, day in enumerate(daysOfTheWeek):
            if not processedFlight.get(day):
                processedFlight[day] = dayOfTheWeek == i

        processedFlight["active"] = True

        processedSchedule[flight["flight_number"]] = processedFlight

    return processedSchedule


def initCSV(code, amountFound):
    f = open("schedule.csv", "w")

    date1 = datetime.now()
    date2 = date1 - timedelta(days=8)

    f.write(
        f"# Schedule autogenerated by a program made by Adam Turaj\n# Data from Flightaware\n# {amountFound} flights were found for {code} between {date2.isoformat(timespec='seconds')} and {date1.isoformat(timespec='seconds')}\n# Start of data:\n"
    )

    data = [
        "number",
        "dep",
        "arr",
        "type",
        "duration",
        "mon",
        "tue",
        "wed",
        "thu",
        "fri",
        "sat",
        "sun",
        "airframes",
        "active",
    ]

    writer = csv.DictWriter(f, data, delimiter=",")

    writer.writeheader()

    return writer, f


if __name__ == "__main__":
    responses = []

    try:
        print("What is the ICAO code for your airline?")
        responses.append(input())

        print("Are you looking to fetch new data?")
        responses.append(input("y/n: ").strip().lower() == "y")

        if responses[1]:
            print(
                "To fetch the data you must have an API key from Flightaware. This can be done by signing up at this URL: https://www.flightaware.com/aeroapi/signup/personal\nCredit given by personal account should account for this process."
            )
            responses.append(input("Once you have gotten the API key enter it here: "))
        else:
            responses.append("")

            print(
                "Is there a json file named 'data.json' with formatted data from Flightaware?"
            )
            if input("y/n: ").strip().lower() == "n":
                print(
                    "You must have a json file to pull cached data from. Please run the program again with the file in the same directory as this program."
                )
                exit(1)
    except KeyboardInterrupt:
        print("Exiting...")
        exit(0)

    main(*responses)
